# Navie Bays 



$$ P(A|B) = \frac {P(A).P(B|A)} {P(B)} $$


or 

$$ \text {Posterior Probability}  = \frac {\text(Prior Probability).\text(Likelihood)} {\text (Normalizing Constant)} $$
<p><b>Posterior Probability</b> - Which Represents the degree to which we believe a                       given model accurately describes the situation given the                       available data and all of our prior knowledge </p>

<p><b>Prior Probability</b> - Which Describe the Degree to which we believe the model
                   accurately describes reality based on all of our information <p>
    
<p> <b>Likelihood</b> - which describes how well the model predicts the data </p>
    
<p><b>Normalizing constant</b> - The constant that makes the posterior density                         INTEGRATE to one</p>
    

In [1]:
import pandas as pd
import numpy as np 

In [2]:
df  = pd.read_csv('navie_bays_play.csv')

In [3]:
df

outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

$$ P({A} |{B}) = \frac {P(A)P(B|A)} {P(B)}$$

$$ P(A) = \text{P(play=yes) } $$
$$ P(B)  = P(outlook=rainy)P(tempreature=mild)P(humidity=normal)P(Wind=strong) $$

### Question  Find prob. for 
#### outlook = "rainy", tempreature = "mild" , humidity="normal", windy = "True"

## Probability of Outlook_ Rainy_Yes

In [4]:
outlook_rainy_yes = df['outlook'][(df["outlook"]=='rainy') & (df["play"]=='yes') ].count()
p_outlook_rainy_yes =outlook_rainy_yes / df['play'][df['play'] == "yes"].count()
p_outlook_rainy_no = 1 - p_outlook_rainy_yes
print("Probability Outlook rainy yes : ",p_outlook_rainy_yes)
print("Probability Outlook rainy no : ",p_outlook_rainy_no)

Probability Outlook rainy yes :  0.3333333333333333
Probability Outlook rainy no :  0.6666666666666667


# Probability of Temperature_Mild_Yes

In [5]:
temperature_mild_yes = df['temperature'][(df["temperature"]=='mild') & (df["play"]=='yes') ].count()
p_temperature_mild_yes =temperature_mild_yes / df['play'][df['play'] == "yes"].count()
p_temperature_mild_no = 1 - p_temperature_mild_yes
print("Probability Temperature mild yes : ",p_temperature_mild_yes)
print("Probability Outlook rainy no : ",p_temperature_mild_no)

Probability Temperature mild yes :  0.4444444444444444
Probability Outlook rainy no :  0.5555555555555556


# Probability of Humidity_Normal_Yes

In [6]:
humidity_normal_yes = df['humidity'][(df["humidity"]=='normal') & (df["play"]=='yes') ].count()
p_humidity_normal_yes =humidity_normal_yes / df['play'][df['play'] == "yes"].count()
p_humidity_normal_no = 1 - p_humidity_normal_yes
print("Probability Humidity Normal yes : ",p_humidity_normal_yes)
print("Probability Humidity Normal no : ",p_humidity_normal_no)

Probability Humidity Normal yes :  0.6666666666666666
Probability Humidity Normal no :  0.33333333333333337


# Probability of Windy_True_Yes

In [7]:
windy_true_yes = df['windy'][(df["windy"] == np.bool_("True")) & (df["play"] == 'yes')].count()
p_windy_true_yes = windy_true_yes / df['play'][df['play'] == "yes"].count()
p_windy_true_no = 1 - p_windy_true_yes
print("Probability Windy True yes : ",p_windy_true_yes)
print("Probability Windy True no : ",p_windy_true_no)

Probability Windy True yes :  0.3333333333333333
Probability Windy True no :  0.6666666666666667


# Checking Ans

In [8]:
Probability_of_yes = p_outlook_rainy_yes * p_temperature_mild_yes * p_humidity_normal_yes * p_windy_true_yes 
Probability_of_no = p_outlook_rainy_no * p_temperature_mild_no * p_humidity_normal_no * p_windy_true_no 

In [9]:
print("Question  Find prob. for ")
print("""Outlook = "rainy", tempreature = "mild" , humidity="normal", windy = "True" """)
if Probability_of_yes > Probability_of_no:
    print("Answer = Yes")
else:
    print("Answer = No")

Question  Find prob. for 
Outlook = "rainy", tempreature = "mild" , humidity="normal", windy = "True" 
Answer = No


# Now Using Sklearn

<p><b>First Change Categorical Data into Numerical data</b>   1,2,3    </p>

In [10]:
df['outlook'] = df['outlook'].map({
    'sunny':1, 'rainy':2, 'overcast':3
})

In [11]:
df['temperature'] = df['temperature'].map({
    'hot':1, 'mild':2,'cool':3
})

In [12]:
df['humidity'] = df['humidity'].map({
    'high':1,'normal':2
})

In [13]:
df['windy'] = df['windy'].map({
    True:1,False:2
})

In [14]:
df

outlook  temperature  humidity  windy play
0         1            1         1      2   no
1         1            1         1      1   no
2         3            1         1      2  yes
3         2            2         1      2  yes
4         2            3         2      2  yes
5         2            3         2      1   no
6         3            3         2      1  yes
7         1            2         1      2   no
8         1            3         2      2  yes
9         2            2         2      2  yes
10        1            2         2      1  yes
11        3            2         1      1  yes
12        3            1         2      2  yes
13        2            2         1      1   no

In [15]:
# import MultinomialNB from sklearn naive_bayes
from sklearn.naive_bayes import MultinomialNB 

In [16]:
clf = MultinomialNB() # create classifier

In [17]:
clf.fit(df.drop('play',axis=1),df['play'])  ## fit features and target
##  features --> df.drop('play',axis=1) ,
## target --> df['play']

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [18]:
df.columns

Index(['outlook', 'temperature', 'humidity', 'windy', 'play'], dtype='object')

In [19]:
data = [
    
    [2,2,2,1],
    [1,2,1,2]
]

In [20]:
clf.predict(data)
## prediction for above data

array(['yes', 'yes'], dtype='<U3')

#### This is for accuracy test

In [21]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
# accuracy_score(y_test,pred)
# confusion_matrix(y_test,pred)

#### Probabillity that we can play the game.

$$ P(Play=yes) = ? $$
$$ P(Play=no) = ? $$


In [22]:
c_yes = df.groupby(by='play')['outlook'].count()

In [23]:
c_yes

play
no     5
yes    9
Name: outlook, dtype: int64

$$ \text{P(play=yes)} =  {\frac {9} {14} }  = 0.0642$$ 
$$ \text{P(play=no)} = {\frac {5} {14} } = 0.3571$$ 

###### Probability We can play the game given ?
    Outlook = Sunny
    Temp = Cool
    Humidity = Hig
    Wind = Strong
    Play = yes

    P(Outlook=Sunny|Play=Yes) = 2 / 9
    P(Temp=Cool|Play=Yes) = 3/9
    P(Humidity=High|Play=yes) = 3/9
    P(Wind=Strong|Play=yes) =  3/9
    P(Play=Yes) = 9/14
    

###### Probability We can not play the game ? 

    P(Outlook=Sunny|Play=No) = 3 / 5
    P(Temp=Cool|Play=No) = 1/5
    P(Humidity=High|Play=No) = 4/5
    P(Wind=Strong|Play=No) =  3/5
    P(Play=No) = 5/14

P(X|C)P(C) or 

    P(X|Play=Yes)P(Play=Yes) = (2/9)*(3/9)*(3/9)*(3/9)*(9/14) = 0.0053
    P(X|Play=No)P(Play=No) =   (3/5)*(1/5)*(4/5)*(3/5)*(5/14) = 0.0206
    
    
    P(X) = P(Outlook=Sunny)*P(Temperature=Cool)*P(Humidity=High)*P(Wind=Strong)
    P(X) = (5/14)*(4/14)*(7/14)*(6/14)
    P(X) = 0.02186
    
    Dividing the results by this value : 
    
    P(Play=yes|X) = 0.0053/0.02186 = 0.2424
    P(Play=No|X) = 0.0206/0.02186 = 0.9421

### IRIS --> MultinomialNB

In [24]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [25]:
from sklearn import datasets

In [26]:
iris = datasets.load_iris()

In [27]:
iris['data'][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [28]:
features = iris['data']
target = iris.target

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,target)

In [30]:
clf = MultinomialNB()

In [31]:
clf.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [32]:
pred = clf.predict(X_test)

In [33]:
## Accuracy Test
accuracy_score(y_test,pred)

0.6842105263157895

In [34]:
## Confusion Matrix
confusion_matrix(y_test,pred)

array([[13,  0,  0],
       [ 0,  3, 12],
       [ 0,  0, 10]], dtype=int64)

In [35]:
data = np.array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
                 [5.9, 3. , 5.1, 1.8]
                ])

In [36]:
clf.predict(data) ## answer is 0,0,2 

array([0, 0, 2])

In [38]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])